development:
  adapter: postgresql
  encoding: unicode
  database: rubyindia-web_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: rubyindia-web_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: rubyindia-web_production
  pool: 5
